### PR TITLE
Metric params & small fixes

### PR DESCRIPTION
**Pull request by calmyournerves**
* Adds the ability pass query params to metrics requests (from & to date)
* Updates the campaign name attribute to use the right attribute from the API response
* Updates the link to the API docs in the README

### CODE REVIEW

**Comment by thechrisoshow** [comment]
Nice!

**Comment by thechrisoshow** [comment]
(This has now been pushed as v 0.2.0)

**Comment by calmyournerves** [comment]
That was quick, thank you! Appreciate it :)

**Comment by thechrisoshow** [comment]
Nono- thank YOU.

I see that they've got a v2 of their api - I have done NOTHING to investigate this yet

**Pull request merged**
